export type PageConfig = {
  id?: string;
  sales_heading: string;
  sales_intro: string;
  sales_benefits: string[];
  sales_closing: string;
  sales_image_url: string;
  cta_heading: string;
  cta_body: string;
  cta_button_text: string;
  cta_url: string;
  title: string;
  subtitle: string;
  cta_text: string;
  deliverable_empty_state: string;
  header_image_url: string;
  convertkit_form_id: string;
  convertkit_fields: Record<string, string>;
  form_fields?: Array<{
    id: string;
    label: string;
    placeholder: string;
    type: string;
    required: boolean;
    isEmailField?: boolean;
    options?: Array<{ id: string; value: string }>;
    hasOtherOption?: boolean;
    otherOptionPlaceholder?: string;
    variableName: string;
  }>;
};