// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fltadufbhxigcynilefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdGFkdWZiaHhpZ2N5bmlsZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NzQ3MDEsImV4cCI6MjA0OTQ1MDcwMX0._Vv1IUv4Lw3VnD1b4jz_wuwlC0hU_FBngFZLK0h7mx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);